Repository odpf/compass, pull requests merged in 2021-11, with the labels that each got.

#20 feat(lineage): move lineage to record
  api/handlers/lineage_handler.go
  api/handlers/lineage_handler_test.go
  api/handlers/type_handler.go
  api/handlers/type_handler_white_box_test.go
  lineage/adjacency.go
  lineage/adjacency_test.go
  lineage/builder.go
  lineage/builder_test.go
  lineage/cache.go
  lineage/graph.go
  lineage/graph_test.go
  lineage/lineage.go
  models/lineage.go
  models/lineage_test.go
  models/record.go
  models/type.go
Labels: enhancement

#21 fix: encoded urn not matched properly to routes
  api/middlewares.go
  api/routes.go
Labels: enhancement

#22 fix(store): urn is not encoded when requesting to elasticsearch
  store/record_repository.go
Labels: bug

#23 feat!: change record filter behaviour
  api/handlers/search_handler.go
  api/handlers/search_handler_test.go
  api/handlers/type_handler_test.go
  api/handlers/utils.go
  store/record_repository.go
  store/record_repository_test.go
  store/search.go
  store/search_test.go
  store/testdata/dagger-id.json
  store/testdata/dagger-service.json
  store/testdata/dagger-th-deployed.json
  store/testdata/dagger-vn-id.json
  store/testdata/dagger.json
  store/testdata/search-test-fixture.json
Labels: bug, enhancement

#24 fix: remove newrelic debug logging
  cmd/serve.go
Labels: bug

#35 chore: add issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation
